services:
  tellyseerr:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tellyseerr
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - tellyseerr_data:/app/jellyseerr_bot.db

volumes:
  tellyseerr_data:
